#!/usr/bin/env bash

set -euo pipefail
export DOCKER_IMAGE="gcr.io/banba-group/jonathanclarke-ie:${BUILDKITE_COMMIT}"
echo "--- :kubernetes: deploying ${DOCKER_IMAGE} to kubernetes"

if [ -z "${DOCKER_IMAGE:-}" ]; then
  echo ":boom: \$DOCKER_IMAGE missing" 1>&2
  exit 1
fi

manifest="$(mktemp)"
echo '--- :kubernetes: Shipping'
gcloud config set project banba-group
gcloud config set run/region us-central1
gcloud run deploy jonathanclarke-ie --image $DOCKER_IMAGE
