#!/usr/bin/env bash

set -euo pipefail
export DOCKER_IMAGE="gcr.io/banba-group/jonathanclarke-ie:${BUILDKITE_COMMIT}"
echo "--- :kubernetes: deploying ${DOCKER_IMAGE} to kubernetes"

if [ -z "${DOCKER_IMAGE:-}" ]; then
  echo ":boom: \$DOCKER_IMAGE missing" 1>&2
  exit 1
fi

manifest="$(mktemp)"
echo '--- :kubernetes: Shipping'
gcloud config set project banba-group
gcloud container clusters get-credentials production --zone us-central1
envsubst < k8s/production/deployment.yaml > "${manifest}"
kubectl apply -f "${manifest}"

echo '--- :zzz: Waiting for deployment'

ATTEMPTS=0
ROLLOUT_STATUS_CMD="kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie"
until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 100 ]; do
    $ROLLOUT_STATUS_CMD
    ATTEMPTS=$((attempts + 1))
    echo "."
    sleep 10
done

if ! kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie; then
    echo "Failed to deploy; rolling back the deployment"
    kubectl rollout undo deployment jonathanclarke-ie --namespace=jonathanclarke-ie
    kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie
    exit 1
fi
