steps:
  - label: ":docker: Docker Login"
    key: docker-login
    command:
      - buildkite-agent secret get DOCKERHUB_VAYU_TOKEN | docker login -u $$(buildkite-agent secret get DOCKERHUB_VAYU_USERNAME) --password-stdin

  - label: ":jekyll: Build & Audit"
    key: build
    depends_on: docker-login
    timeout_in_minutes: 20
    command:
      - apk add --no-cache git build-base
      - bundle config set with 'ci'
      - bundle config set without 'development'
      - bundle install
      - bundle audit check --update
      - bundle exec jekyll build
      - tar czf _site.tar.gz _site/
    artifact_paths:
      - _site.tar.gz
    plugins:
      - docker#v5.11.0:
          image: "ruby:4.0.1-alpine"

  - label: ":mag: HTML Validation"
    key: html-validation
    depends_on: build
    timeout_in_minutes: 20
    command:
      - buildkite-agent artifact download _site.tar.gz .
      - tar xzf _site.tar.gz
      - gem install html-proofer
      - htmlproofer _site --ignore-urls "/^http:/" --no-enforce-https --allow-missing-href
    plugins:
      - docker#v5.11.0:
          image: "ruby:4.0.1-alpine"
