---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "blog-beilabs-com"
  namespace: "blog-beilabs-com"
  labels:
    app: "blog-beilabs-com"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  replicas: 3
  selector:
    matchLabels:
      app: "blog-beilabs-com"
  template:
    metadata:
      labels:
        app: "blog-beilabs-com"
    spec:
      containers:
        - name: "blog-beilabs-com"
          image:  "${DOCKER_IMAGE}"
          imagePullPolicy: "Always"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 100          
          ports:
          - containerPort: 80
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "blog-beilabs-com-hpa"
  namespace: "blog-beilabs-com"
  labels:
    app: "blog-beilabs-com"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "blog-beilabs-com"
    apiVersion: "apps/v1"
  minReplicas: 3
  maxReplicas: 6
---
apiVersion: v1
kind: LimitRange
metadata:
  name: blog-beilabs-com-limit-range
  namespace: "blog-beilabs-com"
spec:
  limits:
  - default:
      memory: 25Mi
    defaultRequest:
      memory: 15Mi
    type: Container
