---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "jonathanclarke-ie"
  namespace: "jonathanclarke-ie"
  labels:
    app: "jonathanclarke-ie"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: "jonathanclarke-ie"
  template:
    metadata:
      labels:
        app: "jonathanclarke-ie"
    spec:
      containers:
        - name: "jonathanclarke-ie"
          image:  "${DOCKER_IMAGE}"
          imagePullPolicy: "Always"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 100          
          ports:
          - containerPort: 80
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "jonathanclarke-ie-hpa"
  namespace: "jonathanclarke-ie"
  labels:
    app: "jonathanclarke-ie"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "jonathanclarke-ie"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 6
# ---
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: jonathanclarke-ie-limit-range
#   namespace: "jonathanclarke-ie"
# spec:
#   limits:
#   - default:
#       memory: 25Mi
#     defaultRequest:
#       memory: 15Mi
#     type: Container
